### ISSUE TITLE
A few suggestions for your package

### ISSUE THREAD

**Issue by tuxette** [LMJL-Alea/ktest#10]
- [Bug?] `check_python` is not exported (not in object) while it is advised to use it sometimes when installing the package
- [Bug?] since you gave the alias `ktest` to the package documentation, the documentation of the function `ktest` cannot be accessed
- a minimal code example with data (or datasets described in the README of `r-pkg`) would be more than welcome :-)

**Comment by gdurif** [comment]
Thanks for the report. I am currently working on a package slight refactoring. All this issue should be addressed.
It will be released today or tomorrow.
Best

**Comment by gdurif** [comment]
Hi, it is available, see the dedicated README in `r-pkg` sub-directory.

Do not hesitate if you encounter any issues.

Best

**Comment by tuxette** [comment]
Sorry for my late reply: we tested it and it works perfectly! Thanks a lot.

**Comment by gdurif** [comment]
No problem, thanks for the update. If needed, I am implementing a small helper function to save the results which is a bit tricky (because a Python objects exposed to R through reticulate).
It should be available soon.

**Comment by gdurif** [comment]
Hi, just a quick FYI if you are still using the package.

I've done some modifications in the way `reticulate` manages Python requirements under the hood, which is now totally seamless for the end user (leveraging the "new" function `reticulate::py_requires()` which uses [`uv`](https://docs.astral.sh/uv/) Python package and project manager).

Edit (I have forgotten the most important part): This new version breaks retro-compatibility so that you may have to modify your previous codes. If you want to use the former version of the package and keep your existing codes as is, you just need to install the former version of the package with:
```r
remotes::install_github("LMJL-Alea/ktest", ref = "r_v1.0.1_latest", subdir = "r-pkg")
```

**Comment by tuxette** [comment]
Thanks for the hint! I am not using it at the moment but that doesn't mean that I won't in the next few months.
